server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://192.168.157.133:61616
#    user: admin
#    password: admin
    close-timeout: 15s
    in-memory: true
    non-blocking-redelivery: false #是否在回滚消息之前停止消息传递，启动，消息不被保存
    send-timeout: 0 # wait forever
    queue-name: myQueue
    topic-name: myTopic

  packages:
    trust-all: true

  pool:
    enabled: true
    max-connections: 10
    idle-timeout: 30000

  jms:
    pub-sub-domain: false # topic use this settings


